### PR TITLE
Add run command to test program with exercise args

### LINKED ISSUE #22: Run Command
In the output of exercises there is a small description of commands to run to do certain tasks. One of these is a run command which should run a given program with the arguments that would be given when calling verify. Problem here is that the run command is currently aliased to MenuCommand.

I've got this running locally just going to write some tests for it and then I'll get a PR up for review :+1:

### PR DESCRIPTION
**Pull request by mikeymike**
Resolves #22

### CODE REVIEW

**Comment by mikeymike** [comment]
Resolves #22

**Comment by AydinHassan** [comment]
Hey dude, unfortunately this won't work anymore. With the changes i'm bringing in #23. The `getArgs` function is moved to the `StdOutExerciseCheck` interface. The new `CgiOutputExerciseCheck` doesn't use `getArgs`.

I'm not really sure how you can overcome this ATM. I would say to use the ExerciseRunner and grab the output from the `Result` classes, but that means you would have to switch the instance of the Result class to see what it is. 

We maybe need to have a chat about this.

**Comment by mikeymike** [comment]
Oki doke, I'll hold off on this one then there will probably a lot more work involved with the CGI stuff anyway.

**Comment by AydinHassan** [comment]
Sorry dude would have warned you earlier , I didn't realise it would affect it

**Comment by mikeymike** [comment]
Not a problem dude, I'll take another look at it once you finish up #23 :+1:

**Comment by AydinHassan** [comment]
I did most of it today just a test or two

**Pull request closed without merging**
